export enum PRODUCT_ACTIONS {
  ADD_PRODUCT = "ADD_PRODUCT",
  ADD_ALL_PRODUCTS = "ADD_ALL_PRODUCTS"
}

export enum STATE_ACTIONS {
    REFRESH_STATE = "REFRESH_STATE",
    REFRESH_CASE = "REFRESH_CASE"
  }